### ISSUE TITLE
A question of ContractParameter.FromJson(ByteString)

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-modules#293]
Now we get `ByteString` type of result's stack when invoke contract, it's `StackItemType`.
In RpcClient, we convert stack use:
https://github.com/neo-project/neo-modules/blob/dcd946a25b8f3e6365a42bfe3ecf68be990f8b6c/src/RpcClient/Models/RpcInvokeResult.cs#L47

but in `ContractParameter.FromJson(JObject json)`  is no  `ByteString`  type, it's should be `ContractParameterType`:
https://github.com/neo-project/neo/blob/b47157669cabc9c4f0f4ff56cf4fe2a82905bcfe/src/neo/SmartContract/ContractParameter.cs#L58

Can we support `StackItemType` convert to `ContractParameterType`  or `StackItem.FromJson(JObject json)` etc ?

**Comment by shargon** [comment]
Could you make a unit test for reproduce the issue?  I don't understand very well the problem

**Comment by devhawk** [comment]
@shargon  #300

**Comment by ProDog** [comment]
@shargon I have updated unit test for this issue, please have a look at it https://github.com/neo-project/neo-modules/pull/301 .

**Comment by Qiao-Jin** [comment]
This issue is caused by reading json of StackItem as ContractParameter, and I doubt whether this is correct ... And it seems that StackItemType & ContractParameterType are not accordance in more than one types:

ContractParameterType.ByteArray
ContractParameterType.String
ContractParameterType.Hash160
ContractParameterType.Hash256
ContractParameterType.PublicKey
ContractParameterType.Signature
ContractParameterType.Void

&

StackItemType.Pointer
StackItemType.ByteString
StackItemType.Buffer
StackItemType.Struct

**Comment by Tommo-L** [comment]
Both RpcServer and RpcClient use `StackItemType`?

**Comment by ProDog** [comment]
Only RpcClient need to deal with the invokescript's result.
