### ISSUE TITLE
Preview3 tag

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-modules#306]
Can we please get a preview3 tag? Makes it easier to sync all projects to the right compatible commits. Thanks

**Comment by superboyiii** [comment]
@ixje Tag will be added when release. Current preview3 branch is under test.

**Comment by ixje** [comment]
Oh. Do you have a time estimate? because the vm and core already seem to have preview3 tags. Thanks again.

**Comment by superboyiii** [comment]
> estimate

Yep. As we planned here [preview3-release-plan](https://github.com/neo-project/neo/issues/1731), neo-cli v3.0.0-preview3 will be released on August 3rd as well as neon(the compiler) and tag will added on each repository. We've already updated neo-vm and neo because we've tested them and need them as dependency in nodes, modules and devpack. Thanks for your advice.
