### ISSUE TITLE
Restart consensus node will cause InvalidOperationException

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#724]
**Describe the bug**
Restart consensus node will cause InvalidOperationException

**To Reproduce**
1. Create a private chain, whatever single consensus or 4 consensus
2. Start consensus and stop
3. Restart

**Expected behavior**
`System.InvalidOperationException: Operation is not valid due to the current state of the object.`
Persist could still go on.

**Screenshots**
![image](https://user-images.githubusercontent.com/38493437/172315200-f4288159-f54d-4bc6-ac59-82ccdd055adc.png)

**Comment by ZhangTao1596** [comment]
This is because we save consensus context when commit. When you restart, cn tries loading context from storage which is a context from last block and height check fail here https://github.com/neo-project/neo-modules/blob/b9eaa9d84992ce92316f30d1e5e9372914582c49/src/DBFTPlugin/Consensus/ConsensusContext.cs#L271
This won't affect new consensus process.
